### ISSUE TITLE
Update Getting Started Guide for 2.13.0

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/website#15]
There is a new Getting Started Guide for 2.13.0, which needs to be added to the web pages that reference that PDF on this web page:

https://sites.google.com/a/lbl.gov/seed/getting-started

Here is a link to the new PDF

https://drive.google.com/file/d/1LNPzAoaDEeEpn3d46k080X495iGTIbrn/view?usp=sharing

**Comment by RDmitchell** [comment]
@nllong -- not sure who can do this, but I never figured out how to work on the website, so hopefully someone on your side can make this change. Thx !

**Comment by nllong** [comment]
> There is a new Getting Started Guide for 2.13.0, which needs to be added to the web pages that reference that PDF on this web page:
> 
> https://sites.google.com/a/lbl.gov/seed/getting-started
> 
> Here is a link to the new PDF
> 
> https://drive.google.com/file/d/1LNPzAoaDEeEpn3d46k080X495iGTIbrn/view?usp=sharing

@kflemin  -- can you update the seed-platform website with Robin's new PDF in the comment above? Thanks!
